services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
  terraform:
    build:
      context: .
    volumes:
      - ./infrastructure:/infrastructure
    entrypoint: sh
