services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
  terraform:
    build:
      context: .
    environment:
      - TF_LOG_PATH=/infrastructure/terraform.log
      - TF_LOG_PROVIDER=DEBUG
    volumes:
      - ./infrastructure:/infrastructure
    entrypoint: sh
